services:
  nggaweweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nggaweweb
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - nggawe-data:/app/data
      - nggawe-uploads:/app/public/uploads
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.nggawe-web.rule=Host(`nggawe.web.id`)
      - traefik.http.routers.nggawe-web.entrypoints=websecure
      - traefik.http.routers.nggawe-web.tls.certresolver=letsencrypt
      - traefik.http.routers.nggawe-web-http.rule=Host(`nggawe.web.id`)
      - traefik.http.routers.nggawe-web-http.entrypoints=web
      - traefik.http.routers.nggawe-web-http.middlewares=nggawe-web-redirect
      - traefik.http.middlewares.nggawe-web-redirect.redirectscheme.scheme=https
      - traefik.http.services.nggawe-web.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true

volumes:
  nggawe-data:
  nggawe-uploads:
